---
- name: install Apache Web Server
  hosts: all

  tasks:
  - name: install Apache webserver
    apt: name=apache2 state=latest

  - name: Start Apache and Enable it on the every boot
    service: name=apache2 state=started enabled=yes
